"""Add strongs_concordance_cache table

Revision ID: 3d5d4db09863
Revises: 55b96c9ef74a
Create Date: 2025-09-05 18:43:28.957888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5d4db09863'
down_revision = '55b96c9ef74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strongs_concordance_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strongs_number', sa.String(length=10), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strongs_concordance_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strongs_concordance_cache_strongs_number'), ['strongs_number'], unique=True)

    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        # First add the column as nullable
        batch_op.add_column(sa.Column('query_text', sa.Text(), nullable=True))
    
    # Update existing rows to copy query to query_text
    op.execute("UPDATE search_cache SET query_text = query WHERE query_text IS NULL")
    
    # Now make the column non-nullable
    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.alter_column('query_text', nullable=False)
        batch_op.drop_index(batch_op.f('ix_search_cache_query'))
        batch_op.drop_index(batch_op.f('ix_search_cache_query_hash'))
        batch_op.create_index(batch_op.f('ix_search_cache_query_hash'), ['query_hash'], unique=True)
        batch_op.drop_column('query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_search_cache_query_hash'))
        batch_op.create_index(batch_op.f('ix_search_cache_query_hash'), ['query_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_cache_query'), ['query'], unique=True)
        batch_op.drop_column('query_text')

    with op.batch_alter_table('strongs_concordance_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strongs_concordance_cache_strongs_number'))

    op.drop_table('strongs_concordance_cache')
    # ### end Alembic commands ###
