"""Initial migration with all models

Revision ID: 49d45f10f5dd
Revises: 
Create Date: 2025-09-05 13:03:11.728244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d45f10f5dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('testament', sa.String(length=10), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('preferred_perspectives', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('verse_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verse_range_start', sa.Integer(), nullable=False),
    sa.Column('verse_range_end', sa.Integer(), nullable=False),
    sa.Column('user_question', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verse_range_end'], ['verses.id'], ),
    sa.ForeignKeyConstraint(['verse_range_start'], ['verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verse_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse_range_start', sa.Integer(), nullable=False),
    sa.Column('verse_range_end', sa.Integer(), nullable=False),
    sa.Column('selected_text_hash', sa.String(length=64), nullable=False),
    sa.Column('perspectives', sa.JSON(), nullable=False),
    sa.Column('cross_references', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['verse_range_end'], ['verses.id'], ),
    sa.ForeignKeyConstraint(['verse_range_start'], ['verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verse_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verse_summaries_selected_text_hash'), ['selected_text_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verse_summaries_selected_text_hash'))

    op.drop_table('verse_summaries')
    op.drop_table('user_notes')
    op.drop_table('user_analyses')
    op.drop_table('verses')
    op.drop_table('chapters')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
