"""Add search cache table

Revision ID: 55b96c9ef74a
Revises: 2c0859e05df3
Create Date: 2025-09-05 17:52:58.537902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b96c9ef74a'
down_revision = '2c0859e05df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_cache_query'), ['query'], unique=True)
        batch_op.create_index(batch_op.f('ix_search_cache_query_hash'), ['query_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_cache_query_hash'))
        batch_op.drop_index(batch_op.f('ix_search_cache_query'))

    op.drop_table('search_cache')
    # ### end Alembic commands ###
