"""Add Strong's concordance support

Revision ID: bd81529b4baa
Revises: 49d45f10f5dd
Create Date: 2025-09-05 13:15:23.028614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd81529b4baa'
down_revision = '49d45f10f5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strongs_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strongs_number', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('transliteration', sa.String(length=100), nullable=True),
    sa.Column('pronunciation', sa.String(length=100), nullable=True),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('kjv_usage', sa.Text(), nullable=True),
    sa.Column('root_word', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strongs_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strongs_entries_strongs_number'), ['strongs_number'], unique=True)

    op.create_table('verse_strongs_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('strongs_number', sa.String(length=10), nullable=False),
    sa.Column('word_position', sa.Integer(), nullable=False),
    sa.Column('grammatical_info', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verse_strongs_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verse_strongs_mappings_strongs_number'), ['strongs_number'], unique=False)

    with op.batch_alter_table('verses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_with_strongs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strongs_numbers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verses', schema=None) as batch_op:
        batch_op.drop_column('strongs_numbers')
        batch_op.drop_column('text_with_strongs')

    with op.batch_alter_table('verse_strongs_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verse_strongs_mappings_strongs_number'))

    op.drop_table('verse_strongs_mappings')
    with op.batch_alter_table('strongs_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strongs_entries_strongs_number'))

    op.drop_table('strongs_entries')
    # ### end Alembic commands ###
