"""Fix verse_strongs_mappings created_at column

Revision ID: c4ffbc3ae93d
Revises: bd81529b4baa
Create Date: 2025-09-05 13:19:02.329798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ffbc3ae93d'
down_revision = 'bd81529b4baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strongs_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('definition',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('root_word')

    with op.batch_alter_table('verse_strongs_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse_strongs_mappings', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('strongs_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_word', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('definition',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
