"""Add messianic prophecies table

Revision ID: df2accd2aa67
Revises: drop_metadata_tables
Create Date: 2025-09-11 08:45:50.055275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2accd2aa67'
down_revision = 'drop_metadata_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messianic_prophecies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('BIRTH_CIRCUMSTANCES', 'GENEALOGY_LINEAGE', 'GEOGRAPHIC_LOCATIONS', 'MINISTRY_MISSION', 'CHARACTER_ATTRIBUTES', 'DEATH_CRUCIFIXION', 'RESURRECTION_EXALTATION', 'SECOND_COMING', 'KINGDOM_REIGN', 'PRIESTLY_WORK', 'PROPHETIC_OFFICE', 'DIVINE_NATURE', name='prophecycategory'), nullable=False),
    sa.Column('prophecy_verse_start', sa.Integer(), nullable=False),
    sa.Column('prophecy_verse_end', sa.Integer(), nullable=False),
    sa.Column('fulfillment_references', sa.JSON(), nullable=False),
    sa.Column('fulfillment_explanation', sa.Text(), nullable=False),
    sa.Column('generated_from_book', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prophecy_verse_end'], ['verses.id'], ),
    sa.ForeignKeyConstraint(['prophecy_verse_start'], ['verses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messianic_prophecies')
    # ### end Alembic commands ###
